name: CI with gradlew

on:
  push:
    branches: [ main,master ]
  pull_request:
    branches: [ main,maser ]
    
jobs:
  build:

     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
         java-version: '11'
         distribution: 'temurin'
         cache: maven
     - name: Build with Maven
       run: mvn -B package --file pom.xml 
       
     - name: Checkout
       uses: actions/checkout@v2
        
     - name: Run Datree Policy Check
       uses: datreeio/action-datree@main
       with:
         path: '**/*.yaml'
         cliArguments: '--only-k8s-files'
