name: CI with gradlew

on:
  push:
    branches: [ main,master ]
  pull_request:
    branches: [ main,maser ]

env: 
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 
    
jobs:
  build:

     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
         java-version: '11'
         distribution: 'temurin'
         cache: maven
     - name: Build with Maven
       run: mvn -B package --file pom.xml
   
     - name: install datree
       run: curl https://get.datree.io | /bin/bash

     - name: run datree policy check
       run: datree test ~/.datree/k8s-demo.yaml       # you should given the k8s confige file name.
     
     - name: login to the docker hub
       uses: docker/login-action@v2
       with:    # if u use the registry to store the application given the registry url like this and if use the docker hub u dont want the user registry name
         registry: u have to givem the nexus ip 
         username: ${{ secrets.DOCKER_USERAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
